# Generated by Django 4.0.1 on 2022-01-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Superuser'), (1, 'Staff'), (2, 'Applicant')], null=True),
        ),
    ]
