# Generated by Django 4.0.1 on 2022-01-20 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount_allocated', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2022)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('budget', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subcounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subcounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.subcounty')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('family_status', models.CharField(choices=[('orphan', 'Total Orphan'), ('single_parent', 'Single Parent (Without Source of Income)'), ('partial_orphan', 'Partial Orphan (Mother/Father Alive) Without Source of Income'), ('both_parents', 'Both Parents Alive Without Source of Income')], max_length=15)),
                ('death_cert_father', models.FileField(null=True, upload_to='death_certs/')),
                ('death_cert_mother', models.FileField(null=True, upload_to='death_certs/')),
                ('name_of_guardian', models.CharField(max_length=120)),
                ('contact_of_guardian', models.CharField(max_length=13)),
                ('disability_status', models.BooleanField(default=False)),
                ('disability_description', models.TextField(blank=True, null=True)),
                ('admission_number', models.CharField(max_length=30)),
                ('class_of_study', models.PositiveSmallIntegerField()),
                ('award_status', models.CharField(choices=[('pending', 'Pending'), ('awarded', 'Awarded'), ('not_awarded', 'Not Awarded')], max_length=200)),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.level')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.period')),
                ('subcounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.subcounty')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.ward')),
            ],
        ),
    ]
