# Generated by Django 4.0.1 on 2022-01-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
