# Generated by Django 4.0.1 on 2022-01-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
