# Generated by Django 4.0.1 on 2022-01-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='disability_registration_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
