# Generated by Django 4.0.1 on 2022-01-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_application_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='disability_registration_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
