# Generated by Django 4.0.1 on 2022-01-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_alter_application_disability_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='award_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awarded', 'Awarded'), ('not_awarded', 'Not Awarded')], default='pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='application',
            name='death_cert_father',
            field=models.FileField(blank=True, null=True, upload_to='death_certs/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='death_cert_mother',
            field=models.FileField(blank=True, null=True, upload_to='death_certs/'),
        ),
    ]
