# Generated by Django 4.0.1 on 2022-02-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_alter_application_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='school_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='school_recommendation_letter',
            field=models.FileField(blank=True, null=True, upload_to='recommendations/'),
        ),
    ]
