# Generated by Django 4.0.1 on 2022-02-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_application_school_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='disability_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
