# Generated by Django 4.0.1 on 2022-02-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_alter_application_disability_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
