# Generated by Django 4.0.1 on 2022-02-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_alter_application_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
